# InferenceMAX 数据管道配置文件

# 数据源配置
source:
  base_url: "https://inferencemax.semianalysis.com/"
  timeout: 600  # 网页超时时间（秒）
  retry_attempts: 3  # 失败重试次数
  retry_delay: 5  # 重试间隔（秒）

# 目标模型和序列配置
targets:
  models:
    - "Llama 3.3 70B Instruct"
    - "gpt-oss 120B"
    - "DeepSeek R1 0528"

  sequences:
    - "1K / 1K"
    - "1K / 8K"
    - "8K / 1K"

# 文件路径配置
paths:
  base_dir: "/root/semi-bench"
  raw_data_dir: "json_data/raw_json_files"
  output_dir: "json_data"
  archive_dir: "inference_max_pipeline/data_archive"
  log_dir: "inference_max_pipeline/logs"
  report_dir: "inference_max_pipeline/reports"

# 数据清理配置
cleanup:
  min_file_size: 1024  # 最小文件大小（字节）
  require_numeric_data: true  # 是否要求数值数据
  remove_empty_files: true  # 是否删除空文件

# 版本控制配置
versioning:
  enabled: true
  max_versions: 30  # 保留的最大版本数
  compression: true  # 是否压缩历史版本
  date_format: "%Y%m%d_%H%M%S"  # 版本日期格式

# 日志配置
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  max_file_size: "10MB"  # 日志文件最大大小
  backup_count: 5  # 保留的日志文件数量
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# 监控配置
monitoring:
  enabled: true
  check_data_quality: true
  expected_min_records: 1000  # 期望的最小记录数
  alert_on_failure: true

# 通知配置（可选）
notifications:
  email:
    enabled: false
    smtp_server: ""
    smtp_port: 587
    username: ""
    password: ""
    recipients: []

  webhook:
    enabled: false
    url: ""

# 调度配置
scheduling:
  enabled: true   # 是否启用自动调度
  cron_expression: "0 1 * * *"  # 每天凌晨1点执行
  timezone: "UTC"

# 性能配置
performance:
  max_concurrent_downloads: 3  # 最大并发下载数
  request_timeout: 30  # 请求超时（秒）
  page_load_timeout: 10  # 页面加载超时（秒）

# 输出文件配置
output:
  final_csv: "inference_max_latest.csv"
  prefix: "inference_max_"
  timestamp_format: "%Y%m%d_%H%M%S"